stages:
- stage: Build
  displayName: 'Build .NET App'
  jobs:
  - job: BuildJob
    displayName: 'Build and Publish Artifact'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages for Project $(projectPath)'
      inputs:
        command: 'restore'
        projects: '$(projectPath)'
        feedsToUse: 'select' 

    - task: DotNetCoreCLI@2
      displayName: 'Build Project $(projectPath)'
      inputs:
        command: 'build'
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Project $(projectPath)'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api --no-build'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ponabri-api-artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
        ArtifactName: 'ponabri-api-artifact'
        publishLocation: 'Container'